using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace Ruitk.EditorSupport.HMR
{
    /// <summary>
    /// Generates the hot-side <c>__Exports</c> C# source for a member-bearing .uitkx
    /// file from its parsed DirectiveSet. The generated code is compiled into a
    /// temporary HMR assembly whose values/methods/hook bodies are then swapped into
    /// the project assembly by the static/method/delegate swappers
    /// (<see cref="UitkxHmrDelegateSwapper.SwapHooks"/> et al.).
    ///
    /// All DirectiveSet / MemberDeclaration access is via reflection because
    /// <c>Ruitk.Language.dll</c> is loaded dynamically at runtime.
    /// (The legacy {Stem}Hooks container Emit path, its refresh companion, and
    /// EmitModules were removed in the 0.16.0 legacy wave — EmitExports below is
    /// the only emitter.)
    /// </summary>
    internal static class HmrHookEmitter
    {
        // ── Hook alias substitution (mirrors HmrCSharpEmitter) ───────────────
        //
        // Sourced from Ruitk.Core.HookRegistry — the single source of
        // truth shared by SG, HMR, IDE diagnostics, hover docs, and VDG stubs.

        private static readonly (string From, string To)[] s_hookAliases =
            global::Ruitk.Core.HookRegistry.GetAliasTable();

        private static readonly Regex s_genericHookAliasRe = new Regex(
            global::Ruitk.Core.HookRegistry.GetGenericHookPattern(),
            RegexOptions.Compiled
        );

        private static readonly Regex s_setterLambdaRe = new Regex(
            @"\b(set[A-Z][a-zA-Z0-9_]*)\(\s*(?=[a-zA-Z_][a-zA-Z0-9_]*\s*=>|\([^)]*\)\s*=>)",
            RegexOptions.Compiled
        );

        private static string EscapeStringLiteral(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        /// <summary>
        /// Emits the hot-side <c>__Exports</c> unit for a NEW-MODE (plain-declaration) file
        /// (ES-modules campaign, U-02/U-06 — mirror of the SG's ExportsEmitter shapes the
        /// swappers consume):
        /// <list type="bullet">
        ///   <item><description>value → <c>public static {Type} {Name} = {init};</c> with
        ///   <c>[UitkxHmrSwap]</c> so the module static swapper copies the fresh value onto the
        ///   project assembly's identically-FullName'd <c>{ns}.__Exports</c>;</description></item>
        ///   <item><description>util → a plain <c>public static</c> method — the module METHOD
        ///   swapper re-binds the project's <c>__hmr_{Name}_h*</c> delegate to it BY NAME;</description></item>
        ///   <item><description>hook → <c>__{name}_body</c> method for
        ///   <c>UitkxHmrDelegateSwapper.SwapHooks</c> (container "__Exports"), plus the refresh
        ///   companion re-registering <c>{ns}.__Exports::{name}</c> family keys.</description></item>
        /// </list>
        /// Returns empty when the file has no member declarations (or an old Language.dll
        /// without the MemberDeclarations model).
        /// </summary>
        public static string EmitExports(object directives, string filePath,
            string effectiveNs = null,
            IReadOnlyDictionary<string, string> hookKeyMap = null,
            IReadOnlyList<string> bridgeLines = null)
        {
            string ns = effectiveNs ?? (string)GetProp(directives, "Namespace") ?? "Ruitk.Generated";
            var memberDecls = GetProp(directives, "MemberDeclarations");

            var memberList = new List<object>();
            if (memberDecls is IEnumerable enumerable)
                foreach (var item in enumerable)
                    memberList.Add(item);
            // A file with only aliased/default member IMPORTS still needs its __Exports (the
            // bridges live there — audit H1/H4 parity with ExportsEmitter.CollectBridges).
            if (memberList.Count == 0 && (bridgeLines == null || bridgeLines.Count == 0))
                return string.Empty;

            string linePath = NormalizePath(filePath);

            var sb = new StringBuilder(2048);
            sb.AppendLine("// <auto-generated — HMR __Exports bodies />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("#pragma warning disable CS0105, CS8600, CS8601, CS8602, CS8603, CS8604");
            sb.AppendLine();

            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using Ruitk;");
            sb.AppendLine("using Ruitk.Core;");
            sb.AppendLine("using Ruitk.Core.Animation;");
            sb.AppendLine("using Ruitk.Router;");
            sb.AppendLine("using Ruitk.Props.Typed;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using static Ruitk.Props.Typed.StyleKeys;");
            sb.AppendLine("using static Ruitk.Props.Typed.CssHelpers;");
            sb.AppendLine("using static Ruitk.AssetHelpers;");
            sb.AppendLine("using UColor = UnityEngine.Color;");

            sb.AppendLine("using Color = UnityEngine.Color;");
            sb.AppendLine("using EasingFunction = UnityEngine.UIElements.EasingFunction;");
            sb.AppendLine("using EasingMode = UnityEngine.UIElements.EasingMode;");
            sb.AppendLine("using BackgroundRepeat = UnityEngine.UIElements.BackgroundRepeat;");
            sb.AppendLine("using BackgroundPosition = UnityEngine.UIElements.BackgroundPosition;");
            sb.AppendLine("using BackgroundSize = UnityEngine.UIElements.BackgroundSize;");
            sb.AppendLine("using TransformOrigin = UnityEngine.UIElements.TransformOrigin;");
            sb.AppendLine("using BackgroundPositionKeyword = UnityEngine.UIElements.BackgroundPositionKeyword;");
            sb.AppendLine("using BackgroundSizeType = UnityEngine.UIElements.BackgroundSizeType;");
            sb.AppendLine("using Repeat = UnityEngine.UIElements.Repeat;");
            sb.AppendLine("using Length = UnityEngine.UIElements.Length;");
            sb.AppendLine("using StyleKeyword = UnityEngine.UIElements.StyleKeyword;");
            sb.AppendLine("using TextAutoSizeMode = UnityEngine.UIElements.TextAutoSizeMode;");
            // Unity 6.3+ types — preprocessor-guarded so pre-6.3 builds compile clean.
            sb.AppendLine("#if UNITY_6000_3_OR_NEWER");
            sb.AppendLine("using FilterFunction = UnityEngine.UIElements.FilterFunction;");
            sb.AppendLine("using Ratio = UnityEngine.UIElements.Ratio;");
            sb.AppendLine("using StyleRatio = UnityEngine.UIElements.StyleRatio;");
            sb.AppendLine("using MaterialDefinition = UnityEngine.UIElements.MaterialDefinition;");
            sb.AppendLine("using StyleMaterialDefinition = UnityEngine.UIElements.StyleMaterialDefinition;");
            sb.AppendLine("#endif");
            sb.AppendLine();

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            // User + injected usings INSIDE the namespace (mirror of the SG's ExportsEmitter):
            // file-keyed namespaces make sibling file stems enclosing-namespace members, which
            // shadow file-level using-aliases — inside-the-namespace usings win that lookup.
            var usings = GetProp(directives, "Usings");
            if (usings is IEnumerable usingList)
                foreach (var u in usingList)
                    sb.AppendLine($"    using {UitkxHmrCompiler.GlobalizeUsingPayload(u?.ToString())};");
            sb.AppendLine("    public static partial class __Exports");
            sb.AppendLine("    {");

            var hookMembers = new List<object>();
            foreach (var m in memberList)
            {
                string kind = GetProp(m, "Kind")?.ToString();
                string name = (string)GetProp(m, "Name");
                string returnType = (string)GetProp(m, "ReturnTypeText");
                string paramsText = (string)GetProp(m, "ParamsText") ?? string.Empty;
                string body = (string)GetProp(m, "BodyText") ?? string.Empty;
                bool exprBodied = GetProp(m, "IsExpressionBodied") is bool eb && eb;
                int bodyStartLine = GetProp(m, "BodyStartLine") is int bsl ? bsl : 1;
                // F9 generic declaration heads: verbatim `<T, U>` (or empty). Reflective read
                // tolerates an older Language.dll without the property (null -> non-generic).
                string typeParams = GetProp(m, "TypeParamsText") as string ?? string.Empty;

                body = HmrCSharpEmitter.ResolveAssetPaths(body, filePath);

                if (string.Equals(kind, "Value", StringComparison.Ordinal))
                {
                    string type = returnType ?? ExtractNewInitializerTypeName(body) ?? "object";
                    sb.AppendLine();
                    sb.AppendLine("        [global::Ruitk.UitkxHmrSwap]");
                    sb.AppendLine($"#line {bodyStartLine} \"{linePath}\"");
                    sb.AppendLine($"        public static {type} {name} = {body};");
                    sb.AppendLine("#line hidden");
                    continue;
                }

                if (string.Equals(kind, "Hook", StringComparison.Ordinal))
                {
                    hookMembers.Add(m);
                    string hookRet = NormalizeVoidReturn(returnType);
                    string hookBody = exprBodied ? "return " + body + ";" : body;
                    hookBody = ApplyHookAliases(hookBody);
                    sb.AppendLine();
                    sb.AppendLine($"        public static {hookRet} __{name}_body{typeParams}({paramsText})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"#line {bodyStartLine} \"{linePath}\"");
                    sb.AppendLine($"            {hookBody}");
                    sb.AppendLine("#line hidden");
                    sb.AppendLine("        }");
                    continue;
                }

                // Util: a plain public static method — the module METHOD swapper re-binds the
                // project's __hmr_{Name}_h* delegate to it by method name + signature.
                string utilRet = NormalizeVoidReturn(returnType);
                sb.AppendLine();
                if (exprBodied)
                {
                    sb.AppendLine($"#line {bodyStartLine} \"{linePath}\"");
                    sb.AppendLine($"        public static {utilRet} {name}{typeParams}({paramsText}) => {body};");
                    sb.AppendLine("#line hidden");
                }
                else
                {
                    sb.AppendLine($"        public static {utilRet} {name}{typeParams}({paramsText})");
                    sb.AppendLine("        {");
                    sb.AppendLine($"#line {bodyStartLine} \"{linePath}\"");
                    sb.AppendLine($"            {body}");
                    sb.AppendLine("#line hidden");
                    sb.AppendLine("        }");
                }
            }

            // Bridges (U-03): the same internal static forwarding lines the SG's ExportsEmitter
            // emits — rendered by the shared ImportScopeFacts.ComputeImportedMemberBridgeLines
            // and passed in by the compiler (reflection seam).
            if (bridgeLines != null && bridgeLines.Count > 0)
            {
                sb.AppendLine();
                foreach (var bl in bridgeLines)
                    sb.AppendLine(bl);
            }

            sb.AppendLine("    }");

            // Refresh companion: re-register each hook under the FRESH signature, with the
            // U-06 family key {ns}.__Exports::{name} — mirrors ExportsEmitter's companion.
            if (hookMembers.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
                sb.AppendLine("    [global::System.Runtime.CompilerServices.CompilerGenerated]");
                sb.AppendLine("    internal static class __Exports__UitkxHookRefresh");
                sb.AppendLine("    {");
                sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
                sb.AppendLine("        internal static void __Register()");
                sb.AppendLine("        {");
                foreach (var m in hookMembers)
                {
                    string hookName = (string)GetProp(m, "Name");
                    string hookBody = (string)GetProp(m, "BodyText") ?? string.Empty;
                    bool eb2 = GetProp(m, "IsExpressionBodied") is bool b2 && b2;
                    if (eb2) hookBody = "return " + hookBody + ";";
                    string sig = HmrCSharpEmitter.ExtractHookSignature(hookBody) ?? string.Empty;
                    string[] hookCustomKeys = UitkxHmrCompiler.QualifyHookKeys(
                        HmrCSharpEmitter.ExtractCustomHookFamilyKeys(hookBody), hookKeyMap);
                    string familyKey = ns + ".__Exports::" + hookName;
                    string keysLit = HmrCSharpEmitter.RenderCustomHookFamilyKeysLiteral(hookCustomKeys);
                    sb.AppendLine(
                        $"            global::Ruitk.Refresh.RefreshRuntime.RegisterHook(" +
                        $"\"{EscapeStringLiteral(familyKey)}\", " +
                        $"\"{EscapeStringLiteral(sig)}\", " +
                        $"{keysLit});");
                }
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>Extracts <c>T</c> from a <c>new T {...}</c>/<c>new T(...)</c> initializer —
        /// mirror of <c>ExportsEmitter.ExtractInitializerTypeName</c> (G-04 inference sugar).</summary>
        internal static string ExtractNewInitializerTypeName(string initText)
        {
            if (string.IsNullOrEmpty(initText))
                return null;
            string t = initText.TrimStart();
            if (!t.StartsWith("new", StringComparison.Ordinal))
                return null;
            int p = 3;
            while (p < t.Length && (t[p] == ' ' || t[p] == '\t')) p++;
            int start = p;
            int depth = 0;
            while (p < t.Length)
            {
                char c = t[p];
                if (c == '<') { depth++; p++; continue; }
                if (c == '>') { depth--; p++; continue; }
                if (depth == 0 && (c == '{' || c == '(' || c == ' ' || c == '\t' || c == '\r' || c == '\n'))
                    break;
                if (depth == 0 && c == '[')
                {
                    while (p < t.Length && t[p] != ']') p++;
                    if (p < t.Length) p++;
                    continue;
                }
                p++;
            }
            string name = t.Substring(start, p - start).Trim();
            return name.Length > 0 ? name : null;
        }

        private static string NormalizeVoidReturn(string returnType)
            => string.IsNullOrEmpty(returnType) ? "void" : returnType;

        // ── Helpers ───────────────────────────────────────────────────────────

        private static string ApplyHookAliases(string code)
        {
            code = s_setterLambdaRe.Replace(code, "$1.Set(");

            if (
                code.IndexOf("use", StringComparison.Ordinal) < 0
                && code.IndexOf("provideContext", StringComparison.Ordinal) < 0
            )
                return code;

            code = s_genericHookAliasRe.Replace(
                code,
                m =>
                {
                    string hookName = m.Groups[1].Value;
                    string typeArgs = m.Groups[2].Value;
                    string pascalName = char.ToUpper(hookName[3]) + hookName.Substring(4);
                    return $"Hooks.Use{pascalName}{typeArgs}(";
                }
            );

            foreach (var (from, to) in s_hookAliases)
                code = code.Replace(from, to);

            return code;
        }

        private static string NormalizePath(string path)
        {
            return path.Replace("\\", "/");
        }

        private static object GetProp(object obj, string propName)
        {
            // Records expose properties; use GetProperty first, then fall back to GetField
            var prop = obj.GetType().GetProperty(propName);
            if (prop != null)
                return prop.GetValue(obj);
            var field = obj.GetType().GetField(propName);
            return field?.GetValue(obj);
        }
    }
}
